CREATE TABLE "partner_applications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organizationName" varchar(255) NOT NULL,
	"contactName" varchar(255) NOT NULL,
	"contactEmail" varchar(255) NOT NULL,
	"websiteUrl" varchar(500),
	"organizationType" varchar(50) NOT NULL,
	"description" text NOT NULL,
	"capabilities" text NOT NULL,
	"motivation" text NOT NULL,
	"location" varchar(255),
	"teamSize" varchar(50),
	"establishedYear" integer,
	"previousExperience" text,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"reviewedBy" varchar(42),
	"reviewedAt" timestamp,
	"reviewNotes" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "partners" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"shortDescription" varchar(500),
	"capabilities" text,
	"logoUrl" varchar(500),
	"websiteUrl" varchar(500),
	"contactEmail" varchar(255),
	"partnerType" varchar(50) NOT NULL,
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"location" varchar(255),
	"establishedYear" integer,
	"teamSize" varchar(50),
	"specialization" jsonb,
	"achievements" jsonb,
	"projects" jsonb,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"deletedBy" varchar(42),
	"deleteReason" text
);
